name: "KW: CloudFlare - Create Tunnel"
description: "Creates CloudFlare ZeroTrust Tunnel"
author: "KouraWealth"

inputs:
  id:
    description: "Tunnel id"
  name:
    description: "Tunnel name"
  config:
    description: "Indicates if this is a locally ('local') or remotely ('cloudflare') configured tunnel"
    default: "cloudflare"
  account_id:
    description: "CloudFlare Account ID"
    required: true
  token:
    description: "CloudFlare API token"
    required: true

outputs:
  id:
    description: "Tunnel ID"
  token:
    description: "Tunnel access token"

runs:
  using: "node20"
  main: "main.js"

branding:
  icon: "globe"
  color: "green"
